version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    ports:
      - $MONGO_PORTS:27017
    volumes:
      - ./source/server:/webapp

  elastic:
    build: elastic
    ports:
      - $ELASTIC_PORTS1:9200
      - $ELASTIC_PORTS2:9300
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./source/server:/webapp
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - $SWIFT_PORTS:8080

  nodejs:
    build: nodejs
    command: bash -c "cd /webapp && npm install && npm start"
    volumes:
      - ./source/server:/webapp
      - ./source/client:/client
    ports:
      - $NODEJS_PORTS:3333
    depends_on:
      - mongo
      - elastic
      - swift
      - tsacli      
      - tika
      - kafka
    environment:
      - NODE_ENV=$NODE_ENV
      - LANG=ja_JP.UTF-8

  worker:
    build: nodejs
    command: bash -c "cd /webapp && npm install && npm run worker"
    volumes:
      - ./source/server:/webapp
    ports:
      - 3999
    depends_on:
      - mongo
      - elastic
      - swift
      - tika
      - kafka
    environment:
      - NODE_ENV=$NODE_ENV
      - LANG=ja_JP.UTF-8

  react:
    command: bash -c "cd /webapp && npm install && npm start"
    build: react
    volumes:
      - ./source/client:/webapp
    ports:
      - $REACT_PORTS:3000
    depends_on:
      - nodejs

  tsacli:
    build: tsacli
    command: java -Dspring.config.location="application.yml" -jar tsa_client_api-0.1.2.jar
    volumes:
      - ./tsacli/tsa_client_api-0.1.2:/app
      - ./tsacli/keystore:/app/keystore
    ports:
      - $TSACLI_PORTS:8080

  logstash:
    image: logstash:6.6.0
    command: bin/logstash -i
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elastic

  filebeat:
    build: filebeat
    volumes:
      - ./source/server/logs:/usr/share/filebeat/logs
        
  tika:
    image: docker-tikaserver-jpn:latest
    ports:
      - 19998:9998

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 12181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 29092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tika:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
                                                          
