version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    ports:
      - $MONGO_PORTS:27017
    volumes:
      - ./source/server:/webapp

  elastic:
    build: elastic
    ports:
      - $ELASTIC_PORTS1:9200
      - $ELASTIC_PORTS2:9300
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./source/server:/webapp
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - $SWIFT_PORTS:8080

  nodejs:
    build: nodejs
    command: bash -c "cd /webapp && npm install && npm start"
    volumes:
      - ./source/server:/webapp
      - ./source/client:/client
    ports:
      - $NODEJS_PORTS:3333
    depends_on:
      - mongo
      - elastic
      - swift
      - tsacli
    environment:
      - NODE_ENV=$NODE_ENV
      - LANG=ja_JP.UTF-8

  kibana:
    image: kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - $KIBANA_PORTS:5601
    environment:
      SERVER_NAME: kibana.walter

  tsacli:
    build: tsacli
    command: java -Dspring.config.location="application-production.yml" -jar tsa_client_api-0.1.1.jar
    volumes:
      - ./tsacli/tsa_client_api-0.1.1:/app
    ports:
      - $TSACLI_PORTS:8080

  tika:
    image: docker-tikaserver-jpn:latest
    ports:
      - 19998:9998

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.40
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafkarest:
    image: confluentinc/cp-kafka-rest
    depends_on:
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_HOST_NAME: "kafkarest"
      KAFKA_REST_LISTENERS: "http://kafkarest:8082"

  kafkatopicui:
    image: landoop/kafka-topics-ui
    depends_on:
        - kafkarest
    environment:
      KAFKA_REST_PROXY_URL: "http://kafkarest:8082"
      PROXY: "true"
    ports:
      - "8000:8000"
