version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    ports:
      - $MONGO_PORTS:27017
    volumes:
      - ./source/server:/webapp

  elastic:
    build: elastic
    ports:
      - $ELASTIC_PORTS1:9200
      - $ELASTIC_PORTS2:9300
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./source/server:/webapp
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - $SWIFT_PORTS:8080

  nodejs:
    build: nodejs
    command: bash -c "cd /webapp && npm install && npm start"
    volumes:
      - ./source/server:/webapp
      - ./source/client:/client
    ports:
      - $NODEJS_PORTS:3333
    depends_on:
      - mongo
      - elastic
      - swift
      - tsacli
    environment:
      - NODE_ENV=$NODE_ENV

  kibana:
    image: kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - $KIBANA_PORTS:5601
    environment:
      SERVER_NAME: kibana.walter

  tsacli:
    build: tsacli
    command: java -jar tsa_client_api-0.1.0.jar --spring.profiles.active=production
    volumes:
      - ./tsacli/tsa_client_api-0.1.0:/app
    ports:
      - $TSACLI_PORTS:8080
