version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    ports:
      - $MONGO_PORTS:27017
    volumes:
      - ./source/server:/webapp

  elastic:
    build: elastic
    ports:
      - $ELASTIC_PORTS1:9200
      - $ELASTIC_PORTS2:9300
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./source/server:/webapp
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - $SWIFT_PORTS:8080

  nodejs:
    build: nodejs
    command: bash -c "cd /webapp && npm install && npm start"
    volumes:
      - ./source/server:/webapp
      - ./source/client:/client
    ports:
      - $NODEJS_PORTS:3333
    depends_on:
      - mongo
      - elastic
      - swift
      - tsacli
    environment:
      - NODE_ENV=$NODE_ENV
      - LANG=ja_JP.UTF-8

  react:
    command: bash -c "cd /webapp && npm install && npm start"
    build: react
    volumes:
      - ./source/client:/webapp
    ports:
      - $REACT_PORTS:3000
    depends_on:
      - nodejs

  kibana:
    image: kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - $KIBANA_PORTS:5601
    environment:
      SERVER_NAME: kibana.walter
  
  tsacli:
    build: tsacli
    command: java -Dspring.config.location="application.yml" -jar tsa_client_api-0.1.2.jar
    volumes:
      - ./tsacli/tsa_client_api-0.1.2:/app
      - ./tsacli/keystore:/app/keystore
    ports:
      - $TSACLI_PORTS:8080

  logstash:
    image: logstash:6.6.0
    command: bin/logstash -i
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elastic

  filebeat:
    build: filebeat
    volumes:
      - ./source/server/logs:/usr/share/filebeat/logs
