version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    volumes:
      - ./source/server:/webapp
    restart: always

  elastic:
    build: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./source/server:/webapp
    restart: always

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - 8080:8080
    restart: always

  kibana:
    image: kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.walter
    restart: always
