version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --port 27017
    ports:
      - 27017:27017
    volumes:
      - ./source/server:/webapp
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb
    restart: always

  elastic:
    build: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./source/server:/webapp
      - elastic_data:/usr/share/elasticsearch/data
      - elastic_logs:/usr/share/elasticsearch/logs
    restart: always

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - 8080:8080
    volumes:
      - swift_data:/srv
    restart: always

  kibana:
    image: kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.walter
    restart: always

volumes:
  mongo_data:
  mongo_logs:
  elastic_data:
  elastic_logs:
  swift_data:
